### ISSUE TITLE
WitnessCalculatorCircom2 is still using local fromArray32

### ISSUE THREAD

**Issue by exfinen** [iden3/circom_runtime#19]
In calculateWitness function of WitnessCalculatorCircom2, dropped fromArray32 function is still used, and that makes calls to the function fail.
I assume that it should be replaced by ffjavascript.Scalar.fromArray.

I created PR #18 for this.

**Comment by phated** [comment]
It looks like that `fromArray32` is no longer defined, but the `calculateWitness` function isn't actually called.

@nalinbhardwaj Is my memory correct? Do you think we should remove that function on the class? Or maybe we should rename `calculateWTNSBin` to be consistent?

**Comment by nalinbhardwaj** [comment]
> It looks like that `fromArray32` is no longer defined, but the `calculateWitness` function isn't actually called.
> 
> 
> 
> @nalinbhardwaj Is my memory correct? Do you think we should remove that function on the class? Or maybe we should rename `calculateWTNSBin` to be consistent?

Yep, that's right! Since the latest upgrade to snarkjs (after https://github.com/iden3/snarkjs/pull/121) `calculateWitness` shouldn't be in use anywhere.

Renaming `calculateWTNSBin`, however, would still be a bit of a misnomer since that function produces the entire witness binary with the right formatting itself, whereas `calculateWitness` from Circom 1 needs to use some helper functions from the binFileUtils package to create the witness binary buffer.

**Comment by exfinen** [comment]
@phated I understood. I was trying to retrieve witness values from the wasm file and sym file generated by Circom 2.0 using string keys, and ended up with the calculateWitness function. If the function is to be removed, what should be the right one to use to achieve the goal?
